# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "app-skeleton"
client_id = "5cfde57841e16c0d9e870790f800074e"
application_url = "https://farming-yn-sensitive-articles.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://farming-yn-sensitive-articles.trycloudflare.com/auth/callback",
  "https://farming-yn-sensitive-articles.trycloudflare.com/auth/shopify/callback",
  "https://farming-yn-sensitive-articles.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "crissanclick.myshopify.com"
